elementos_home_page = {
    "home_ticker": "xpath://section[@class='Headband fixed visible']//h2[1]",
    "home_ticker_close": "xpath://img[@alt='close_icon']",
    "home_logocv": "xpath=//img[@class='hidden-xs']",
    "home_input_buscador": "xpath=//input[@placeholder='Buscar']",
    "home_lupa": "xpath=//i[@name='search']",
    "home_avatar": "xpath=//a[@class='dropdown-toggle dropdownUser menu_user custom-menu-user-style hidden-xs']//img[@class='menu_user--img']",
    "home_nodo_inicio": "xpath=//div[contains(text(),'Inicio')]",
    "home_nodo_catalogo": "xpath=//div[contains(text(),'Catálogo')]",
    "home_nodo_generos": "xpath=//div[contains(text(),'Géneros')]",
    "home_nodo_compra": "xpath=//div[contains(text(),'Compra y Renta')]",
    "home_nodo_canales": "xpath=//div[contains(text(),'Canales')]",
    "home_nodo_kids": "xpath=//img[@alt='Kids']",
    "home_nodo_miscontenidos": "xpath=//div[contains(text(),'Mis Contenidos')]",
    "home_nodo_musica": "xpath=//img[@alt='Claro música']",
    "home_superdestacados": "xpath=//section[@class='section02b section-highlight03 padding-top-2']//li[2]//div[1]//div[1]//div[1]//div[1]//div[1]//div[1]//a[1]//span[1]",
    "home_scroll_left_super": "xpath=//div[@class='jcarousel carousel-destacado']//div[@class='scrollinghotspotleft']",
    "home_scroll_right_super": "xpath=//div[@class='jcarousel carousel-destacado']//div[@class='scrollinghotspotright']",
    "home_recomienda": "xpath=//h4[normalize-space()='Claro video te recomienda']",
    "home_carrusel_recomienda": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_recomienda": "xpath=//section[@class='section-carrousel section-recommended horizontal']//div[@class='fa fa-chevron-left fa-2x']",
    "home_scroll_right_recomienda": "xpath=//section[@class='section-carrousel section-recommended horizontal']//div[@class='scrollinghotspotright']",
    "home_paramount": "xpath=//h4[normalize-space()='Paramount+ incluido en Claro video']",
    "home_carrusel_paramount": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[3]/div[2]/div",
    "home_scroll_left_paramount": "xpath=/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/section[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]",
    "home_scroll_right_paramount": "xpath=/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/section[3]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]",
    "home_terror": "xpath=//h4[normalize-space()='Terror en tu pantalla']",
    "home_carrusel_terror": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[4]/div[2]/div",
    "home_scroll_left_terror": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[4]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_terror": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[4]/div[2]/div/div/div[3]/div",
    "home_coleccion": "xpath=//h4[normalize-space()='Colección Claro video']",
    "home_carrrusel_coleccion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div",
    "home_scroll_left_coleccion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[5]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_coleccion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[5]/div[2]/div/div/div[3]/div",
    "home_familia": "xpath=//h4[normalize-space()='Diversión en Familia']",
    "home_carrusel_familia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[6]/div[2]/div",
    "home_scroll_left_familia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[6]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_familia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[6]/div[2]/div/div/div[3]/div",
    "home_compra": "xpath=//h4[normalize-space()='Top de Compra y Renta']",
    "home_carrusel_compra": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_compra": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[7]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_compra": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[7]/div[2]/div/div/div[3]/div",
    "home_maraton": "xpath=//h4[normalize-space()='Maratón de Series']",
    "home_carrusel_maraton": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_maraton": "xpath:/html/body/div[2]/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_maraton": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[3]/div",
    "home_nuevoen": "xpath=//h4[normalize-space()='Lo Nuevo en Claro video']",
    "home_carrusel_nuevoen": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_nuevoen": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_nuevoen": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[3]/div",
    "home_parati": "xpath=//h4[normalize-space()='Para ti']",
    "home_carrusel_parati": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_parati": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_parati": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[3]/div",
    "home_lomasvisto": "xpath=//h4[normalize-space()='Lo más visto']",
    "home_carrusel_lomasvisto": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div[1]/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_lomasvisto": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[11]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_lomasvisto": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[11]/div[2]/div/div/div[3]/div",
    "home_series": "xpath=//h4[normalize-space()='Las mejores series']",
    "home_carrusel_series": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_series": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_series": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[3]/div",
    "home_peliculas": "xpath=//h4[normalize-space()='Las mejores películas']",
    "home_carrusel_peliculas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_peliculas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_peliculas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[3]/div",
    "home_hbo": "xpath=//h4[normalize-space()='HBO']",
    "home_carrusel_hbo": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_hbo": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_hbo": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[3]/div",
    "home_edye": "xpath=//h4[normalize-space()='Edye']",
    "home_carrusel_edye": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_edye": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_edye": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[3]/div",
    "home_noggin": "xpath=//h4[normalize-space()='Noggin']",
    "home_carrusel_noggin": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_noggin": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_noggin": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[3]/div",
    "home_atres": "xpath=//h4[normalize-space()='ATRESplayer']",
    "home_carrusel_atres": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_atres": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_atres": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[3]/div",
    "home_picardia": "xpath=//h4[normalize-space()='Picardía Nacional']",
    "home_carrusel_picardia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_picardia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_picardia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[3]/div",
    "home_qello": "xpath=//h4[normalize-space()='Qello Concerts']",
    "home_carrusel_qello": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_qello": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_qello": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[3]/div",
    "home_karaoke": "xpath=//h4[normalize-space()='Stingray Karaoke']",
    "home_carrusel_karaoke": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_karaoke": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_karaoke": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[3]/div",
    "home_rtveplay": "xpath=//h4[normalize-space()='rtveplay+']",
    "home_carrusel_rtveplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span/i",
    "home_scroll_left_rtveplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_rtveplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[3]/div",
    "home_starzplay": "xpath=//h4[normalize-space()='Starzplay']",
    "home_carrusel_starzplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span/i",
    "home_scroll_left_starzplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_starzplay": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[3]/div",
    "home_accion": "xpath=//h4[normalize-space()='Acción y Aventura']",
    "home_carrusel_accion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_accion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_accion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[3]/div",
    "home_comedia": "xpath=//h4[normalize-space()='Comedia']",
    "home_carrusel_comedia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_comedia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_comedia": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[3]/div",
    "home_suspenso": "xpath=//h4[normalize-space()='Terror y Suspenso']",
    "home_carrusel_suspenso": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_suspenso": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_suspenso": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[3]/div",
    "home_cine": "xpath=//h4[normalize-space()='Cine de Oro']",
    "home_carrusel_cine": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_cine": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_cine": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[3]/div",
    "home_ficcion": "xpath=//h4[normalize-space()='Ciencia Ficción']",
    "home_carrusel_ficcion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_ficcion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_ficcion": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[3]/div",
    "home_drama": "xpath=//h4[normalize-space()='Drama']",
    "home_carrusel_drama": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[2]/div",
    "home_scroll_left_drama": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_drama": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[3]/div",
    "home_romanticas": "xpath=//h4[normalize-space()='Románticas']",
    "home_carrusel_romanticas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[2]/div",
    "home_scroll_left_romanticas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_romanticas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[3]/div",
    "home_niños": "xpath=//h4[normalize-space()='Niños']",
    "home_carrusel_niños": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_niños": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_niños": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[3]/div",
    "home_documentales": "xpath=//h4[normalize-space()='Documentales']",
    "home_carrusel_documentales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[1]/ul/li[3]/div/div/div/div/div/div/a/span",
    "home_scroll_left_documentales": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_documentales": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[3]/div",
    "home_latino": "xpath=//h4[normalize-space()='Latinoamérica']",
    "home_carrusel_latino": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_latino": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_latino": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[3]/div",
    "home_anime": "xpath=//h4[normalize-space()='Anime']",
    "home_carrusel_anime": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_anime": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_anime": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[3]/div",
    "home_infantil": "xpath=//h4[normalize-space()='Series Infantiles']",
    "home_carrusel_infantil": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_infantil": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_infantil": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[3]/div",
    "home_seriesventa": "xpath=//h4[normalize-space()='Series en Venta']",
    "home_carrusel_seriesventa": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_seriesventa": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_seriesventa": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[3]/div",
    "home_epoca": "xpath=//h4[normalize-space()='Películas de Época']",
    "home_carrusel_epoca": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_epoca": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_epoca": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[3]/div",
    "home_musicales": "xpath=//h4[normalize-space()='Musicales']",
    "home_carrusel_musicales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_musicales": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_musicales": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[3]/div",
    "home_independiente": "xpath=//h4[normalize-space()='Cine Independiente']",
    "home_carrusel_independiente": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_independiente": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_independiente": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[3]/div",
    "home_españolas": "xpath=//h4[normalize-space()='Series Españolas']",
    "home_carrusel_españolas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_españolas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[39]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_españolas": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[39]/div[2]/div/div/div[3]/div",
    "home_musica": "xpath=//h4[normalize-space()='Música y Conciertos']",
    "home_carrusel_musica": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_musica": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[40]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_musica": "xpath=/html/body/div[2]/div/div[2]/div[2]/div/div/section[40]/div[2]/div/div/div[3]/div",
    #"home_footer": "xpath: //*[@id='app']/div/div[2]/footer/div",
    #"home_chat": "xpaht=/html/body/div[2]/div/div[2]/footer/div/div[1]/div[4]/ul[1]",
    #"home_tutoenvideo": "xpath=//div//ul//a[@href='https://www.clarovideo.com/tutoriales_en_video']",
    #"home_tutoriales": "xpath=//div//ul//li//a[@href='/tutoriales']",
    #"home_preguntasfrecuentes": "xpath=//div//ul//li//a[@href='/faqs']",
    #"home_requerimientos": "xpath=//div//ul//li//a[@href='/fe/sitesplus/sk_telmex/html/esp/faqs.html#requerimientos']",
    #"home_terminos": "xpath=//div//ul//li//a[@href='/terminos_y_condiciones']",
    #"home_politicas": "xpath=//div//ul//li//a[@href='/politicas_de_privacidad']",
    #"home_promociones": "xpath=//div//ul//li//a[@href='/fe/sitesplus/sk_telmex/html/esp/terminos_promociones.html']",
    #"home_licencia": "xpath=//div//ul//li//a[@href='/licencia_usuario_final']",
    #"home_logo_twitter": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[1]/a/i",
    #"home_logo_fb": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[2]/a",
    #"home_logo_google": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[3]/a",
    #"home_logo_youtube": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[4]/a",

}

elementos_nodo_catalogo_page = {
    "catalogo_subnodo_paramount": "xpath://span[normalize-space()='Paramount+']",
    "catalogo_subnodo_peliculas": "xpath://span[normalize-space()='Películas']",
    "catalogo_subnodo_series": "xpath://span[normalize-space()='Series']",
    "catalogo_subnodo_musica": "xpath://span[normalize-space()='Música']",
    "catalogo_subnodo_deportes": "xpath://span[normalize-space()='Deportes']",
    "catalogo_subnodo_documentales": "xpath://span[normalize-space()='Documentales']",
    "catalogo_subnodo_latinoamericanas": "xpath://span[normalize-space()='Latinoamérica']",
    "catalogo_subnodo_karaoke": "xpath://span[normalize-space()='Karaoke']",
    "catalogo_carrsuel_destacados": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_recomienda": "xpath://h4[normalize-space()='Claro video te recomienda']",
    "catalogo_carrsuel_recomienda": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series": "xpath://h4[normalize-space()='Series de TV']",
    "catalogo_carrsuel_series": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_accion": "xpath://h4[normalize-space()='Películas de Acción']",
    "catalogo_carrusel_accion": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_comedia": "xpath://h4[normalize-space()='Películas de Comedia']",
    "catalogo_carrusel_comedia": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_niños": "xpath://h4[normalize-space()='Niños']",
    "catalogo_carrusel_niños": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_terror": "xpath://h4[normalize-space()='Películas de Terror']",
    "catalogo_carrusel_terror": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_romanticas": "xpath://h4[normalize-space()='Películas Románticas']",
    "catalogo_carrusel_romanticas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div[1]/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_drama": "xpath://h4[normalize-space()='Películas de Drama']",
    "catalogo_carrusel_drama": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_documentales": "xpath://h4[normalize-space()='Documentales']",
    "catalogo_carrusel_documentales": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_conciertos": "xpath://h4[normalize-space()='Conciertos']",
    "catalogo_carrusel_conciertos": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_lomasvisto": "xpath://h4[normalize-space()='Lo más visto']",
    "catalogo_carrusel_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
}

elementos_nodo_catalogo_paramount_page = {
    "catalogo_paramount_logo": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[1]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_bannerseries": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[2]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_bannerpaliculas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[3]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div",
    "catalogo_footer": "xpath://*[@id='app']/div/div[1]/footer",
    "catalogo_paramount_originales": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/section[3]/div[1]/div[1]/h4[1]",
    "catalogo_paramount_carrusel_originales": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_peliculas": "xpath://h4[normalize-space()='Películas']",
    "catalogo_paramount_carrusel_peliculas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_imperdibles": "xpath://h4[normalize-space()='Series Imperdibles']",
    "catalogo_paramount_carrusel_imperdibles": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_inolvidables": "xpath://h4[normalize-space()='Series Inolvidables']",
    "catalogo_paramount_carrusel_inolvidables": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_garantizadas": "xpath://h4[normalize-space()='Diversión Garantizada']",
    "catalogo_paramount_carrusel_garantizadas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_niños": "xpath://h4[normalize-space()='Para los más chiquitos']",
    "catalogo_paramount_carrusel_niños": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_reality": "xpath://h4[normalize-space()='Reality Shows']",
    "catalogo_paramount_carrusel_reality": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_comedia": "xpath://h4[normalize-space()='Series de Comedia']",
    "catalogo_paramount_carrusel_comedia": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_lomasvisto": "xpath://h4[normalize-space()='Lo más visto']",
    "catalogo_paramount_carrusel_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",

}

elementos_nodo_catalogo_peliculas_page = {
    "catalogo_peliculas_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_terecomienda": "xpath://h4[normalize-space()='Claro video te recomienda']",
    "catalogo_peliculas_carrusel_terecomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_mexicanas": "xpath://h4[normalize-space()='Mexicanas']",
    "catalogo_perliculas__mexicanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_perliculas_accion": "xpath://h4[normalize-space()='Acción y Aventura']",
    "catalogo_peliculas_carrusel_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_ficcion": "xpath://h4[normalize-space()='Ciencia Ficción y Fantasía']",
    "catalogo_peliculas_carrusel_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_cine": "xpath://h4[normalize-space()='Cine de Oro']",
    "catalogo_peliculas_carrusel_cine": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_clasicas": "xpath://h4[normalize-space()='Clásicas']",
    "catalogo_peliculas_carrusel_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_comedia": "xpath://h4[normalize-space()='Comedia']",
    "catalogo_peliculas_carrusel_comedia": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_deportes": "xpath://h4[normalize-space()='Deportes']",
    "catalogo_peliculas_carrusel_deportes": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_animados": "xpath://h4[normalize-space()='Dibujos Animados']",
    "catalogo_peliculas_carrusel_animados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_drama": "xpath://h4[normalize-space()='Drama']",
    "catalogo_peliculas_carrusel_drama": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_familiares": "xpath://h4[normalize-space()='Familiares']",
    "catalogo_peliculas_carrusel_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_historicas": "xpath://h4[normalize-space()='Históricas']",
    "catalogo_peliculas_carrusel_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_infantiles": "xpath://h4[normalize-space()='Infantiles']",
    "catalogo_peliculas_carrusel_infantiles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_internacional": "xpath://h4[normalize-space()='Internacional']",
    "catalogo_peliculas_carrusel_internacional": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_musicales": "xpath://h4[normalize-space()='Musicales']",
    "catalogo_peliculas_carrusel_musicales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[16]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_epoca": "xpath://h4[normalize-space()='Películas de Época']",
    "catalogo_peliculas_carrusel_epoca": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_romanticas": "xpath://h4[normalize-space()='Románticas']",
    "catalogo_peliculas_carrusel_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_suspenso": "xpath://h4[normalize-space()='Suspenso']",
    "catalogo_pelicula_carrusel_suspensp": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_terror": "xpath://h4[normalize-space()='Terror']",
    "catalogo_peliculas_carrusel_terror": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_lomasvisto": "xpath://h4[normalize-space()='Lo más visto']",
    "catalogo_peliculas_carrusel_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",

}

elementos_nodo_catalogo_series_page = {
    "catalogo_series_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_recomienda": "xpath://h4[normalize-space()='Claro video te recomienda']",
    "catalogo_series_carrusel_recomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_maraton": "xpath://h4[normalize-space()='Maratón de Series']",
    "catalogo_series_carrusel_maraton": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_soloencv": "xpath://h4[normalize-space()='Sólo en Claro video']",
    "catalogo_series_carrusel_soloencv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_mexicanas": "xpath://h4[normalize-space()='Mexicanas']",
    "catalogo_series_carrusel_mexicanas": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/section[5]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]/i[1]",
    "catalogo_series_accion": "xpath://h4[normalize-space()='Acción y Aventura']",
    "catalogo_series_carrusel_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_anime": "xpath://h4[normalize-space()='Animé y Videojuegos']",
    "catalogo_series_carrusel_anime": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_biograficas": "xpath://h4[normalize-space()='Biográficas']",
    "catalogo_series_carrusel_biograficas": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/section[8]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]/i[1]",
    "catalogo_series_ficcion": "xpath://h4[normalize-space()='Ciencia Ficción']",
    "catalogo_series_carrusel_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_clasicas": "xpath://h4[normalize-space()='Clásicas']",
    "catalogo_series_carrusel_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_comicas": "xpath://h4[normalize-space()='Cómicas']",
    "catalogo_series_carrusel_comicas": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/section[11]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]/i[1]",
    "catalogo_series_dramas": "xpath://h4[normalize-space()='Dramas']",
    "catalogo_series_carrusel_dramas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_españolas": "xpath://h4[normalize-space()='Españolas']",
    "catalogo_series_carrusel_españolas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_familiares": "xpath://h4[normalize-space()='Familiares']",
    "catalogo_series_carrusel_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_historicas": "xpath://h4[normalize-space()='Históricas']",
    "catalogo_series_carrusel_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div[1]/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_infantiles": "xpath://h4[normalize-space()='Infantiles']",
    "catalogo_series_carrusel_infantiles": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/section[16]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]/i[1]",
    "catalogo_series_internacionesles": "xpath://h4[normalize-space()='Internacionales']",
    "catalogo_series_carrusel_internacionales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_latinoamericanas": "xpath://h4[normalize-space()='Latinoamericanas']",
    "catalogo_series_carrusel_latinoamericanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_policiacas": "xpath://h4[normalize-space()='Policíacas']",
    "catalogo_series_carrusel_policiacas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_tv": "xpath://h4[normalize-space()='Programas de TV']",
    "catalogo_series_carrusel_tv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_documentales": "xpath://h4[normalize-space()='Series Documentales']",
    "catalogo_series_carrusel_documentales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[3]/div/div/div/div/div/div/a/span",
    "catalogo_series_romanticas": "xpath://h4[normalize-space()='Románticas']",
    "catalogo_series_carrusel_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[22]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_suspenso": "xpath://h4[normalize-space()='Suspenso y Terror']",
    "catalogo_series_carrusel_suspenso": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[23]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_lomasvisto": "xpath://h4[normalize-space()='Lo más visto']",
    "catalogo_series_carrusel_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[24]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/div/div/label",
}

elementos_plan_selector_page = {
    "planselector_selecciona": "xpath://h1[@class='planselect-title']",
    #BANNER CLARO VIDEO MENSUAL
    #"banner_claro_mensual": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_cv_claro_mensual": "xpath://html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/img[1]",
    "precio_claro_mensual": "xpath:/html/body/div[2]/div/div/div[2]/div/div[1]/div/div/p[1]",
    "periodicidad_claro_mensual": "xpath:/html/body/div[2]/div/div/div[2]/div/div[1]/div/div/p[2]",
    "promocion_claro_mensual": "xpath://html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]",
    "claro_mensual_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/button[1]",
    "claro_mensual_btn_suscribete": "xpath://button[normalize-space()='Suscríbete Mensual']",
    # BANNER CLARO VIDEO ANUAL
    # "banner_claro_anual": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_cv_claro_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/img[1]",
    "precio_claro_anual": "xpath://p[normalize-space()='$1149']",
    "periodicidad_claro_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/p[2]",
    "promocion_claro_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/span[1]",
    "claro_anual_btn_incluye?": "xpath://div[@class='_3sFpy']//div[2]//div[1]//button[1]",
    "claro_anual_btn_suscribete": "xpath://button[normalize-space()='Suscríbete Anual']",
    # BANNER FOX
    # "banner_fox": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_fox": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/img[1]",
    "precio_fox": "xpath://p[normalize-space()='$116']",
    "periodicidad_fox": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/div/p[2]",
    "promocion_fox": "xpath://span[normalize-space()='A partir del 4to. mes $162 / mes']",
    "fox_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye FOX SPORTS?']",
    "fox_btn_suscribete": "xpath://button[normalize-space()='Contrata FOX SPORTS']",
    # BANNER NOGGIN
    # "banner_noggin": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_noggin": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/img[1]",
    "precio_noggin": "xpath://p[normalize-space()='$49']",
    "periodicidad_noggin": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/div/p[2]",
    "promocion_noggin": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/span[1]",
    "noggin_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Noggin?']",
    "noggin_btn_suscribete": "xpath://button[normalize-space()='Contrata NOGGIN']",
    # BANNER EDYE
    # "banner_edye": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_edye": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/img[1]",
    "precio_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/div/p[1]",
    "periodicidad_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/div/p[2]",
    "promocion_edye": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/span[1]",
    "edye_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Edye?']",
    "edye_btn_suscribete": "xpath://button[normalize-space()='Contrata Edye']",
    # BANNER PICARDIA
    # "banner_picardia": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_picardia": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/img[1]",
    "precio_picardia": "xpath://p[normalize-space()='$46']",
    "periodicidad_picardia": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/div/p[2]",
    "promocion_picardia": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/span[1]",
    "picardia_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Picardía Nacional?']",
    "picardia_btn_suscribete": "xpath://button[normalize-space()='Contrata PICARDÍA']",
    # BANNER KARAOKE
    # "banner_karaoke": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_karaoke": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[7]/div[1]/img[1]",
    "precio_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/div/p[1]",
    "periodicidad_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/div/p[2]",
    "promocion_karaoke": "xpath://span[normalize-space()='En Claro video']",
    "karaoke_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Stingray Karaoke?']",
    "karaoke_btn_suscribete": "xpath://button[normalize-space()='Contrata STINGRAY KARAOKE']",
    # BANNER QELLO
    # "banner_qello": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_qello": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[8]/div[1]/img[1]",
    "precio_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/div/p[1]",
    "periodicidad_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/div/p[2]",
    "promocion_qello": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[8]/div[1]/span[1]",
    "qello_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Qello Concerts by Stingray?']",
    "qello_btn_suscribete": "xpath://button[normalize-space()='Contrata Qello Concerts']",
    # BANNER ATRESPLAYER
    # "banner_atres": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_atres": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/img[1]",
    "precio_atres": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/div[1]/p[1]",
    "periodicidad_atres": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/div[1]/p[2]",
    "promocion_atres": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/span[1]",
    "atres_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye ATRESplayer?']",
    "atres_btn_suscribete": "xpath://button[normalize-space()='Contrata ATRESplayer']",
    # BANNER HBO
    # "banner_hbo": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_hbo": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[10]/div[1]/img[1]",
    "precio_hbo": "xpath://p[normalize-space()='$149']",
    "periodicidad_hbo": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[10]/div[1]/div[1]/p[2]",
    "promocion_hbo": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[10]/div[1]/span[1]",
    "hbo_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye HBO?']",
    "hbo_btn_suscribete": "xpath://button[normalize-space()='Contrata HBO']",
    # BANNER INDYCAR
    # "banner_indycar": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_indycar": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/img[1]",
    "precio_indycar": "xpath://p[normalize-space()='$490']",
    "periodicidad_indycar": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/div[1]/p[2]",
    "promocion_indycar": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/span[1]",
    "indycar_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye INDYCAR?']",
    "indycar_btn_suscribete": "xpath://button[normalize-space()='Contrata INDYCAR']",
    # BANNER STARZPLAY
    # "banner_starzplay": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_starzplay": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[12]/div[1]/img[1]",
    "precio_starzplay": "xpath://p[normalize-space()='$89']",
    "periodicidad_starzplay": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[12]/div[1]/div[1]/p[2]",
    "promocion_starzplay": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[12]/div[1]/span[1]",
    "starzplay_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye Starzplay?']",
    "starzplay_btn_suscribete": "xpath://button[normalize-space()='Contrata STARZPLAY']",
    # BANNER RTVE
    # "banner_rtve": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_rtve": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[13]/div[1]/img[1]",
    "precio_rtve": "xpath://p[normalize-space()='$99']",
    "periodicidad_rtve": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[13]/div[1]/div[1]/p[2]",
    "promocion_rtve": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[13]/div[1]/span[1]",
    "rtve_btn_incluye?": "xpath://button[normalize-space()='¿Qué incluye RTVE play +?']",
    "rtve_btn_suscribete": "xpath://button[normalize-space()='CONTRATA RTVE play +']",

}


# Plan selector Claro video que incluye
elementos_incluye_CV_page = {
    "incluye_logo_cv": "xpath://img[@class='what-includes-logo']",
    "incluye_lasmejores": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn2.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_clarovideo_subscriptionDescription_offerOne_logo.png?1623263087']",
    "incluye_verconcv_telemex": "xpath://div[@class='what-includes-content']//div[1]//p[1]",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn2.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_clarovideo_subscriptionDescription_offerTwo_logo.png?1623263239']",
    "inclute_verconcv_telcel": "xpath://div[@class='what-includes-background']//div[2]//p[1]",
    "incluye_promo_mensual": "xpath://p[2]//span[1]",
    "incluye_precio_mensual": "xpath://span[normalize-space()='$115']",
    "incluye_iva_mensual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[3]/span[2]",
    "incluye_periodo_mensual": "xpath://span[normalize-space()='/ mes']",
    "incluye_btn_prueba_mensual": "xpath://div[@class='what-includes-background']//button[1]",
    "incluye_puedes_cancelar_mensual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/p[3]",
    "incluye_promo_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/p[4]/span[1]",
    "incluye_precio_anual": "xpath://span[normalize-space()='$1149']",
    "incluye_iva_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[4]/span[2]",
    "incluye_periodo_anual": "xpath://span[normalize-space()='/ año']",
    "incluye_btn_prueba_anual": "xpath://div[@class='what-includes-background']//button[1]",
    "incluye_puedes_cancelar_anual": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/p[5]",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector FOX que inlcuye
elementos_incluye_fox_page = {
    "incluye_logo_fox": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_fox": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath:/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/img[1]",
    "incluye_verfoxconcv_telmex": "xpath://p[normalize-space()='Ver con FOX en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_fox_subscriptionDescription_offerTwo_logo.png?1629388988']",
    "incluye_visitasitioweb_telcel": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_fox": "xpath://span[@class='what-includes-promo-blue']",
    "incluye_precio_fox": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_fox": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_fox": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_contrata_fox": "xpath://button[contains(text(),'CONTRÁTALO')]",
    "incluye_puedes_cancelar_fox": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector NOGGIN que inlcuye
elementos_incluye_noggin_page = {
    "incluye_logo_noggin": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_noggin": "xpath://p[@class='what-includes-description']",
    #"incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_fox_subscriptionDescription_offerOne_logo.png?1629388804']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con Noggin en Claro video']",
    #"incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_fox_subscriptionDescription_offerTwo_logo.png?1629388988']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_noggin": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_noggin": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_noggin": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_noggin": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_noggin": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector EDYE que inlcuye
elementos_incluye_edye_page = {
    "incluye_logo_edye": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_edye": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn6.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_edye_subscriptionDescription_offerOne_logo.png?1629389524']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con Edye en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn6.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_edye_subscriptionDescription_offerTwo_logo.png?1629390739']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_edye": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_edye": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_edye": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_edye": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_edye": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_edye": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector PICARDIA que inlcuye
elementos_incluye_picardia_page = {
    "incluye_logo_picardia": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_picardia": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn9.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_picardia_nacional_subscriptionDescription_offerOne_logo.png?1629386035']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con Picardía Nacional en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn9.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_picardia_nacional_subscriptionDescription_offerTwo_logo.png?1629386786']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_picardia": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_picardia": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_picardia": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_picardia": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_picardia": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}

# Plan selector KARAOKE que inlcuye
elementos_incluye_karaoke_page = {
    "incluye_logo_karaoke": "xpath://img[@class='what-includes-logo']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn7.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_stingraykaraoke_subscriptionDescription_offerOne_logo.png?1629387131']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con Stingray Karaoke en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn7.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_stingraykaraoke_subscriptionDescription_offerTwo_logo.png?1629386215']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_karaoke": "xpath://span[@class='what-includes-promo-blue']",
    "incluye_precio_karaoke": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_karaoke": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_karaoke": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_karaoke": "xpath://button[@class='what-includes-purchase-button']",
    "incluye_terminos_karaoke": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector QELLO que inlcuye
elementos_incluye_qello_page = {
    "incluye_logo_qello": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_qello": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_stingrayqello_subscriptionDescription_offerOne_logo.png?1629388389']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con Qello Concerts en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_stingrayqello_subscriptionDescription_offerTwo_logo.png?1629388638']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_qello": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_qello": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_qello": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_qello": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_qello": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_qello": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector ATRES que inlcuye
elementos_incluye_atres_page = {
    "incluye_logo_atres": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_atres": "xpath://p[@class='what-includes-description']",
    "incluye_promo_atres": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_atres": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_atres": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_atres": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_atres": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_atres": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector HBO que inlcuye
elementos_incluye_hbo_page = {
    "incluye_logo_hbo": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_hbo": "xpath://p[@class='what-includes-description']",
    "incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_hbo_subscriptionDescription_offerOne_logo.png?1629386398']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con HBO en Claro video']",
    "incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_hbo_subscriptionDescription_offerTwo_logo.png?1629386550']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_hbo": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_hbo": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_hbo": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_hbo": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_hbo": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector INDYCAR que inlcuye
elementos_incluye_indy_page = {
    "incluye_logo_indy": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_indy": "xpath://p[@class='what-includes-description']",
    "incluye_promo_indy": "xpath://span[@class='what-includes-promo-blue']",
    "incluye_precio_indy": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_indy": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_indy": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_indy": "xpath://button[normalize-space()='SUSCRÍBETE AHORA']",
    "incluye_terminos_indy": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector STARZPLAY que inlcuye
elementos_incluye_starz_page = {
    "incluye_logo_starz": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_starz": "xpath://p[@class='what-includes-description']",
    "incluye_promo_starz": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_starz": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_starz": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_starz": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_starz": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_starz": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}
# Plan selector RTVE que inlcuye
elementos_incluye_rtve_page = {
    "incluye_logo_rtve": "xpath://img[@class='what-includes-logo']",
    "incluye_subtitulo_rtve": "xpath://p[@class='what-includes-description']",
    #"incluye_logo_telmex": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_hbo_subscriptionDescription_offerOne_logo.png?1629386398']",
    "incluye_ver_en_cv": "xpath://p[normalize-space()='Ver con RTVE play + en Claro video']",
    #"incluye_logo_telcel": "xpath://img[@alt='https://clarovideocdn5.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/mexico_hbo_subscriptionDescription_offerTwo_logo.png?1629386550']",
    "incluye_visita_sitio_web": "xpath://p[normalize-space()='Visita nuestro sitio web']",
    "incluye_promo_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_rtve": "xpath://span[@class='what-includes-price-amount']",
    "incluye_iva_rtve": "xpath://span[@class='what-includes-iva-message']",
    "incluye_periodo_rtve": "xpath://span[@class='what-includes-price-period']",
    "incluye_btn_prueba_rtve": "xpath://button[normalize-space()='PRUEBA 7 DÍAS SIN COSTO']",
    "incluye_terminos_rtve": "xpath://p[@class='what-includes-disclaimer']",
    "incluye_img1": "xpath://img[@alt='Top poster']",
    "incluye_img2": "xpath://div[@class='what-includes-posters-left']//div[1]//img[1]",
    "incluye_img3": "xpath://div[@class='what-includes-posters-left']//div[2]//img[1]",
    "incluye_img4": "xpath://div[@class='what-includes-posters-left']//div[3]//img[1]",
    "incluye_img5": "xpath://img[@alt='Right poster']",
}