elementos_home_page = {
    "home_ticker": "//div//section//button//h2[text()='Bienvenido a Claro video. Da clic aquí para conocer más planes y acceder a canales Premium.']",
    "home_ticker_close": "xpath=//*[@id='app']/div/section/button[2]/img",
    "home_logocv": "xpath=//*[@id='app']/div/div[2]/header/div/div[1]/a/img",
    "home_input_buscador": "xpath=//*[@id='app']/div/div[2]/header/div/div[2]/form/div/input",
    "home_lupa": "xpath=//*[@id='app']/div/div[2]/header/div/div[2]/form/div/i",
    "home_avatar": "xpath=//*[@id='menuUser']/li/a[1]/a/span[1]",
    "home_nodo_inicio": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[1]/div/div",
    "home_nodo_catalogo": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[2]/div/div",
    "home_nodo_generos": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[3]/div/div",
    "home_nodo_compra": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[4]/div/div",
    "home_nodo_canales": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[5]/div/div",
    "home_nodo_kids": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[6]/div/div",
    "home_nodo_miscontenidos": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[7]/div/div",
    "home_nodo_musica": "xpath=//*[@id='app']/div/div[2]/header/div/div[3]/div/div[8]/div/div",
    "home_superdestacados": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[1]/div",
    "home_scroll_left_super": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[1]/div/div/div/div[2]/div",
    "home_scroll_right_super": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[1]/div/div/div/div[3]/div",
    "home_recomienda": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[2]/div[1]/div/h4",
    "home_carrusel_recomienda": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_recomienda": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[2]/div[2]/div/div/div[2]/div",
    "home_scroll_right_recomienda": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[2]/div[2]/div/div/div[3]/div",
    "home_paramount": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[3]/div[1]/div/h4",
    "home_carrusel_paramount": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[3]/div[2]/div",
    "home_scroll_left_paramount": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[3]/div[2]/div/div/div[2]/div",
    "home_scroll_right_paramount": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[3]/div[2]/div/div/div[3]/div",
    "home_terror": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[4]/div[1]/div/h4",
    "home_carrusel_terror": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[4]/div[2]/div",
    "home_scroll_left_terror": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[4]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_terror": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[4]/div[2]/div/div/div[3]/div",
    "home_coleccion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[5]/div[1]/div/h4",
    "home_scroll_left_coleccion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[5]/div[2]/div/div/div[2]/div/div",
    "home_scroll_rigth_coleccion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[5]/div[2]/div/div/div[3]/div",
    "home_familia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[6]/div[1]/div/h4",
    "home_carrusel_familia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[6]/div[2]/div",
    "home_scroll_left_familia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[6]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_familia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[6]/div[2]/div/div/div[3]/div",
    "home_compra": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[7]/div[1]/div/h4",
    "home_scroll_left_compra": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[7]/div[2]/div/div/div[2]/div/div",
    "home_scroll_rigth_compra": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[7]/div[2]/div/div/div[3]/div",
    "home_maraton": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[8]/div[1]/div/h4",
    "home_carrusel_maraton": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_maraton": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_maraton": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[8]/div[2]/div/div/div[3]/div",
    "home_nuevoen": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[9]/div[1]/div/h4",
    "home_carrusel_nuevoen": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_nuevoen": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_nuevoen": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[9]/div[2]/div/div/div[3]/div",
    "home_parati": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[10]/div[1]/div/h4",
    "home_carrusel_parati": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_parati": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_parati": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[10]/div[2]/div/div/div[3]/div",
    "home_lomasvisto": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[11]/div[1]/div/h4",
    "home_carrusel_lomasvisto": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div[1]/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_lomasvisto": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[11]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_lomasvisto": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[11]/div[2]/div/div/div[3]/div",
    "home_series": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[12]/div[1]/div/h4",
    "home_carrusel_series": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_series": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[2]/div/div",
    "home_scroll_rigth_series": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[12]/div[2]/div/div/div[3]/div",
    "home_peliculas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[13]/div[1]/div/h4",
    "home_carrusel_peliculas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_peliculas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_peliculas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[13]/div[2]/div/div/div[3]/div",
    "home_hbo": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[14]/div[1]/div/h4",
    "home_carrusel_hbo": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_hbo": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_hbo": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[14]/div[2]/div/div/div[3]/div",
    "home_edye": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[15]/div[1]/div/h4",
    "home_carrusel_edye": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_edye": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_edye": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[15]/div[2]/div/div/div[3]/div",
    "home_noggin": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[16]/div[1]/div/h4",
    "home_carrusel_noggin": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_noggin": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_noggin": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[16]/div[2]/div/div/div[3]/div",
    "home_atres": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[17]/div[1]/div/h4",
    "home_carrusel_atres": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_atres": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_atres": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[17]/div[2]/div/div/div[3]/div",
    "home_picardia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[18]/div[1]/div/h4",
    "home_carrusel_picardia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_picardia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[2]/div/div",
    "home_scroll_rigth_picardia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[18]/div[2]/div/div/div[3]/div",
    "home_qello": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[19]/div[1]/div/h4",
    "home_carrusel_qello": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_qello": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_qello": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[19]/div[2]/div/div/div[3]/div",
    "home_karaoke": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[20]/div[1]/div/h4",
    "home_carrusel_karaoke": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_karaoke": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_karaoke": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[20]/div[2]/div/div/div[3]/div",
    "home_accion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[21]/div[1]/div/h4",
    "home_carrusel_accion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_accion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_accion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[21]/div[2]/div/div/div[3]/div",
    "home_comedia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[22]/div[1]/div/h4",
    "home_carrusel_comedia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_comedia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_comedia": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[22]/div[2]/div/div/div[3]/div",
    "home_suspenso": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[23]/div[1]/div/h4",
    "home_carrusel_suspenso": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_suspenso": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_suspenso": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[23]/div[2]/div/div/div[3]/div",
    "home_cine": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[24]/div[1]/div/h4",
    "home_carrusel_cine": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_cine": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_cine": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[24]/div[2]/div/div/div[3]/div",
    "home_ficcion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[25]/div[1]/div/h4",
    "home_carrusel_ficcion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_ficcion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_ficcion": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[25]/div[2]/div/div/div[3]/div",
    "home_drama": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[26]/div[1]/div/h4",
    "home_carrusel_drama": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[2]/div",
    "home_scroll_left_drama": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[3]/div/div",
    "home_scroll_rigth_drama": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[26]/div[2]/div/div/div[3]/div",
    "home_romanticas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[27]/div[1]/div",
    "home_carrusel_romanticas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[2]/div",
    "home_scroll_left_romanticas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[3]/div",
    "home_scroll_rigth_romanticas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[27]/div[2]/div/div/div[3]/div",
    "home_niños": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[28]/div[1]/div/h4",
    "home_carrusel_niños": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_niños": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_niños": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[28]/div[2]/div/div/div[3]/div",
    "home_documentales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[29]/div[1]/div/h4",
    "home_carrusel_documentales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[1]/ul/li[3]/div/div/div/div/div/div/a/span",
    "home_scroll_left_documentales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_documentales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[29]/div[2]/div/div/div[3]/div",
    "home_latino": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[30]/div[1]/div/h4",
    "home_carrusel_latino": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_latino": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_latino": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[30]/div[2]/div/div/div[3]/div",
    "home_anime": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[31]/div[1]/div/h4",
    "home_carrusel_anime": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_anime": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_anime": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[31]/div[2]/div/div/div[3]/div",
    "home_infantil": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[32]/div[1]/div/h4",
    "home_carrusel_infantil": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "home_scroll_left_infantil": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_infantil": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[32]/div[2]/div/div/div[3]/div",
    "home_seriesventa": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[33]/div[1]/div/h4",
    "home_carrusel_seriesventa": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_seriesventa": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_seriesventa": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[33]/div[2]/div/div/div[3]/div",
    "home_epoca": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[34]/div[1]/div/h4",
    "home_carrusel_epoca": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_epoca": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_epoca": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[34]/div[2]/div/div/div[3]/div",
    "home_musicales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[35]/div[1]/div/h4",
    "home_carrusel_musicales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_musicales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_musicales": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[35]/div[2]/div/div/div[3]/div",
    "home_independiente": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[36]/div[1]/div/h4",
    "home_carrusel_independiente": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_independiente": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_independiente": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[36]/div[2]/div/div/div[3]/div",
    "home_españolas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[37]/div[1]/div/h4",
    "home_carrusel_españolas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_españolas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_españolas": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[37]/div[2]/div/div/div[3]/div",
    "home_musica": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[38]/div[1]/div/h4",
    "home_carrusel_musica": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "home_scroll_left_musica": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[2]/div",
    "home_scroll_rigth_musica": "xpath=//*[@id='app']/div/div[2]/div[2]/div/div/section[38]/div[2]/div/div/div[3]/div",
    #"home_footer": "xpath: //*[@id='app']/div/div[2]/footer/div",
    #"home_chat": "xpaht=/html/body/div[2]/div/div[2]/footer/div/div[1]/div[4]/ul[1]",
    #"home_tutoenvideo": "xpath=//div//ul//a[@href='https://www.clarovideo.com/tutoriales_en_video']",
    #"home_tutoriales": "xpath=//div//ul//li//a[@href='/tutoriales']",
    #"home_preguntasfrecuentes": "xpath=//div//ul//li//a[@href='/faqs']",
    #"home_requerimientos": "xpath=//div//ul//li//a[@href='/fe/sitesplus/sk_telmex/html/esp/faqs.html#requerimientos']",
    #"home_terminos": "xpath=//div//ul//li//a[@href='/terminos_y_condiciones']",
    #"home_politicas": "xpath=//div//ul//li//a[@href='/politicas_de_privacidad']",
    #"home_promociones": "xpath=//div//ul//li//a[@href='/fe/sitesplus/sk_telmex/html/esp/terminos_promociones.html']",
    #"home_licencia": "xpath=//div//ul//li//a[@href='/licencia_usuario_final']",
    #"home_logo_twitter": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[1]/a/i",
    #"home_logo_fb": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[2]/a",
    #"home_logo_google": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[3]/a",
    #"home_logo_youtube": "xpath=//*[@id='app']/div/div[2]/footer/div/div[1]/div[5]/ul/li[4]/a",

}

elementos_nodo_catalogo_page = {
    "catalogo_subnodo_paramount": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[1]/span",
    "catalogo_subnodo_peliculas": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[2]/span",
    "catalogo_subnodo_series": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[3]/span",
    "catalogo_subnodo_musica": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[4]/span",
    "catalogo_subnodo_deportes": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[5]/span",
    "catalogo_subnodo_documentales": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[6]/span",
    "catalogo_subnodo_latinoamericanas": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[7]/span",
    "catalogo_subnodo_karaoke": "xpath://*[@id='app']/div/div[1]/header/div/div[4]/div/div[2]/div/div[8]",
    "catalogo_carrsuel_destacados": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_recomienda": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[2]/div[1]/div/h4",
    "catalogo_carrsuel_recomienda": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[3]/div[1]/div/h4",
    "catalogo_carrsuel_series": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_accion": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[1]/div/h4",
    "catalogo_carrusel_accion": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_comedia": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[5]/div[1]/div/h4",
    "catalogo_carrusel_comedia": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_niños": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[6]/div[1]/div/h4",
    "catalogo_carrusel_niños": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_terror": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[7]/div[1]/div/h4",
    "catalogo_carrusel_terror": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_romanticas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[8]/div[1]/div/h4",
    "catalogo_carrusel_romanticas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div[1]/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_drama": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[9]/div[1]/div/h4",
    "catalogo_carrusel_drama": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_documentales": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[10]/div[1]/div/h4",
    "catalogo_carrusel_documentales": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_conciertos": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[1]/div/h4",
    "catalogo_carrusel_conciertos": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[12]/div[1]/div/h4",
    "catalogo_carrusel_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
}

elementos_nodo_catalogo_paramount_page = {
    "catalogo_paramount_logo": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[1]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_bannerseries": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[2]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_bannerpaliculas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div/ul/li[3]/div/div/div/div/div/div/a/img[1]",
    "catalogo_paramount_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div",
    "catalogo_footer": "xpath://*[@id='app']/div/div[1]/footer",
    "catalogo_paramount_originales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[1]/div",
    "catalogo_paramount_carrusel_originales": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_peliculas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[1]/div",
    "catalogo_paramount_carrusel_peliculas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_imperdibles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[1]/div",
    "catalogo_paramount_carrusel_imperdibles": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_inolvidables": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[1]/div",
    "catalogo_paramount_carrusel_inolvidables": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_garantizadas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[1]/div",
    "catalogo_paramount_carrusel_garantizadas": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_niños": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[1]/div",
    "catalogo_paramount_carrusel_niños": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_reality": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[1]/div",
    "catalogo_paramount_carrusel_reality": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_comedia": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[1]/div",
    "catalogo_paramount_carrusel_comedia": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_paramount_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[1]/div/h4",
    "catalogo_paramount_carrusel_lomasvisto": "xpath://*[@id='app']/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",

}

elementos_nodo_catalogo_peliculas_page = {
    "catalogo_peliculas_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_terecomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[1]/div",
    "catalogo_peliculas_carrusel_terecomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_mexicanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[1]/div",
    "catalogo_perliculas__mexicanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_perliculas_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[1]/div",
    "catalogo_peliculas_carrusel_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[1]/div",
    "catalogo_peliculas_carrusel_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_cine": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[1]/div",
    "catalogo_peliculas_carrusel_cine": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[1]/div",
    "catalogo_peliculas_carrusel_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_comedia": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[1]/div",
    "catalogo_peliculas_carrusel_comedia": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_deportes": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[1]/div",
    "catalogo_peliculas_carrusel_deportes": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_animados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[1]/div",
    "catalogo_peliculas_carrusel_animados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_drama": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[11]/div[1]/div",
    "catalogo_peliculas_carrusel_drama": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[1]/div",
    "catalogo_peliculas_carrusel_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[1]/div",
    "catalogo_peliculas_carrusel_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_infantiles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[1]/div",
    "catalogo_peliculas_carrusel_infantiles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_internacional": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[15]/div[1]/div",
    "catalogo_peliculas_carrusel_internacional": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_musicales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[16]/div[1]/div",
    "catalogo_peliculas_carrusel_musicales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[16]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_epoca": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[1]/div",
    "catalogo_peliculas_carrusel_epoca": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[1]/div",
    "catalogo_peliculas_carrusel_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_suspenso": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[1]/div",
    "catalogo_pelicula_carrusel_suspensp": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_terror": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[1]/div",
    "catalogo_peliculas_carrusel_terror": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_peliculas_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[1]/div",
    "catalogo_peliculas_carrusel_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",

}

elementos_nodo_catalogo_series_page = {
    "catalogo_series_destacados": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[1]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_recomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[1]/div",
    "catalogo_series_carrusel_recomienda": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[2]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_maraton": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[1]/div",
    "catalogo_series_carrusel_maraton": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[3]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_soloencv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[1]/div",
    "catalogo_series_carrusel_soloencv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[4]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/div/div/label",
    "catalogo_series_mexicanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[1]",
    "catalogo_series_carrusel_mexicanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[5]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[1]/div",
    "catalogo_series_carrusel_accion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[6]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_anime": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[1]/div",
    "catalogo_series_carrusel_anime": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[7]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_biograficas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[1]/div",
    "catalogo_series_carrusel_biograficas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[8]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[1]/div",
    "catalogo_series_carrusel_ficcion": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[9]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[1]/div",
    "catalogo_series_carrusel_clasicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[10]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_comicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[11]/div[1]/div",
    "catalogo_series_carrusel_comicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[11]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_dramas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[1]/div",
    "catalogo_series_carrusel_dramas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[12]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_españolas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[1]/div",
    "catalogo_series_carrusel_españolas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[13]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[1]/div",
    "catalogo_series_carrusel_familiares": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[14]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[15]/div[1]/div",
    "catalogo_series_carrusel_historicas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div[1]/section[15]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_infantiles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[16]/div[1]/div",
    "catalogo_series_carrusel_infantiles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[16]/div[2]/div/div/div[1]/ul/li[2]/div/div/div/div/div/div/a/span",
    "catalogo_series_internacionesles": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[1]/div",
    "catalogo_series_carrusel_internacionales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[17]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_latinoamericanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[1]/div",
    "catalogo_series_carrusel_latinoamericanas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[18]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_policiacas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[1]/div",
    "catalogo_series_carrusel_policiacas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[19]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_tv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[1]/div",
    "catalogo_series_carrusel_tv": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[20]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_documentales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[1]/div",
    "catalogo_series_carrusel_documentales": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[21]/div[2]/div/div/div[1]/ul/li[3]/div/div/div/div/div/div/a/span",
    "catalogo_series_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[22]/div[1]/div",
    "catalogo_series_carrusel_romanticas": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[22]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_suspenso": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[23]/div[1]/div",
    "catalogo_series_carrusel_suspenso": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[23]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/span",
    "catalogo_series_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[24]/div[1]/div",
    "catalogo_series_carrusel_lomasvisto": "xpath:/html/body/div[2]/div/div[1]/div[2]/div/div/section[24]/div[2]/div/div/div[1]/ul/li[1]/div/div/div/div/div/div/a/div/div/label",
}

elementos_plan_selector_page = {
    "planselector_back": "xpath://*[@id='app']/div/h2",
    "planselector_selecciona": "xpath://*[@id='app']/div/h1",
    #BANNER CLARO VIDEO MENSUAL
    #"banner_claro_mensual": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_cv_claro_mensual": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/img",
    "precio_claro_mensual": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/div/p[1]",
    "periodicidad_claro_mensual": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/div/p[2]",
    "promocion_claro_mensual": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/span",
    "claro_mensual_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/button[1]",
    "claro_mensual_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[1]/div/button[2]",
    # BANNER CLARO VIDEO ANUAL
    # "banner_claro_anual": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_cv_claro_anual": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/img",
    "precio_claro_anual": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/div/p[1]",
    "periodicidad_claro_anual": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/div/p[2]",
    "promocion_claro_anual": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/span",
    "claro_anual_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/button[1]",
    "claro_anual_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[2]/div/button[2]",
    # BANNER FOX
    # "banner_fox": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_fox": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/img",
    "precio_fox": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/div/p[1]",
    "periodicidad_fox": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/div/p[2]",
    "promocion_fox": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/span",
    "fox_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/button[1]",
    "fox_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[3]/div/button[2]",
    # BANNER NOGGIN
    # "banner_noggin": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_noggin": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/img",
    "precio_noggin": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/div/p[1]",
    "periodicidad_noggin": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/div/p[2]",
    "promocion_noggin": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/span",
    "noggin_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/button[1]",
    "noggin_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[4]/div/button[2]",
    # BANNER EDYE
    # "banner_edye": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/img",
    "precio_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/div/p[1]",
    "periodicidad_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/div/p[2]",
    "promocion_edye": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/span",
    "edye_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/button[1]",
    "edye_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[5]/div/button[2]",
    # BANNER PICARDIA
    # "banner_picardia": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_picardia": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/img",
    "precio_picardia": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/div/p[1]",
    "periodicidad_picardia": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/div/p[2]",
    "promocion_picardia": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/span",
    "picardia_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/button[1]",
    "picardia_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[6]/div/button[2]",
    # BANNER KARAOKE
    # "banner_karaoke": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/img",
    "precio_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/div/p[1]",
    "periodicidad_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/div/p[2]",
    "promocion_karaoke": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/span",
    "karaoke_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/button[1]",
    "karaoke_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[7]/div/button[2]",
    # BANNER QELLO
    # "banner_qello": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/img",
    "precio_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/div/p[1]",
    "periodicidad_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/div/p[2]",
    "promocion_qello": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/span",
    "qello_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/button[1]",
    "qello_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[8]/div/button[2]",
    # BANNER ATRESPLAYER
    # "banner_atres": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_atres": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/img",
    "precio_atres": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/div/p[1]",
    "periodicidad_atres": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/div/p[2]",
    "promocion_atres": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/span",
    "atres_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/button[1]",
    "atres_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[9]/div/button[2]",
    # BANNER HBO
    # "banner_hbo": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_hbo": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/img",
    "precio_hbo": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/div/p[1]",
    "periodicidad_hbo": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/div/p[2]",
    "promocion_hbo": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/span",
    "hbo_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/button[1]",
    "hbo_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[10]/div/button[2]",
    # BANNER INDYCAR
    # "banner_indycar": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_indycar": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/img",
    "precio_indycar": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/div/p[1]",
    "periodicidad_indycar": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/div/p[2]",
    "promocion_indycar": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/span",
    "indycar_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/button[1]",
    "indycar_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[11]/div/button[2]",
    # BANNER STARZPLAY
    # "banner_starzplay": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_starzplay": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/img",
    "precio_starzplay": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/div/p[1]",
    "periodicidad_starzplay": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/div/p[2]",
    "promocion_starzplay": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/span",
    "starzplay_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/button[1]",
    "starzplay_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[12]/div/button[2]",
    # BANNER RTVE
    # "banner_rtve": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
    "logo_rtve": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/img",
    "precio_rtve": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/div/p[1]",
    "periodicidad_rtve": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/div/p[2]",
    "promocion_rtve": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/span",
    "rtve_btn_incluye?": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/button[1]",
    "rtve_btn_suscribete": "xpath://*[@id='app']/div/div/div[2]/div/div[13]/div/button[2]",

}


# Plan selector Claro video que incluye
elementos_incluye_CV_page = {
    "incluye_logo_cv": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_lasmejores": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_mensual": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio": "xpath://*[@id='app']/div[1]/div/div[1]/div[1]",
    "incluye_btn_prueba_mensual": "xpath://*[@id='app']/div[1]/div/div[1]/button[1]",
    "incluye_puedes_cancelar": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_promo_anual": "xpath://*[@id='app']/div[1]/div/div[1]/p[4]",
    "incluye_precio": "xpath://*[@id='app']/div[1]/div/div[1]/div[2]",
    "incluye_btn_prueba_anual": "xpath://*[@id='app']/div[1]/div/div[1]/button[2]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector FOX que inlcuye
elementos_incluye_fox_page = {
    "incluye_logo_fox": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_fox": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_fox": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_fox": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_contrata_fox": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_puedes_cancelar_fox": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector NOGGIN que inlcuye
elementos_incluye_noggin_page = {
    "incluye_logo_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_noggin": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector EDYE que inlcuye
elementos_incluye_edye_page = {
    "incluye_logo_edye": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_edye": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_edye": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_edye": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_edye": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_edye": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector PICARDIA que inlcuye
elementos_incluye_picardia_page = {
    "incluye_logo_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_picardia": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}

# Plan selector KARAOKE que inlcuye
elementos_incluye_karaoke_page = {
    "incluye_logo_karaoke": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_promo_karaoke": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_karaoke": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_karaoke": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_karaoke": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector QELLO que inlcuye
elementos_incluye_qello_page = {
    "incluye_logo_qello": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_qello": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_qello": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_qello": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_qello": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_qello": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector ATRES que inlcuye
elementos_incluye_atres_page = {
    "incluye_logo_atres": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_atres": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_atres": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_atres": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_atres": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_atres": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector HBO que inlcuye
elementos_incluye_hbo_page = {
    "incluye_logo_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_hbo": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector INDYCAR que inlcuye
elementos_incluye_indy_page = {
    "incluye_logo_indy": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_indy": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_indy": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_indy": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_indy": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_indy": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector STARZPLAY que inlcuye
elementos_incluye_starz_page = {
    "incluye_logo_starz": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_starz": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_starz": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_starz": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_starz": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_starz": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}
# Plan selector RTVE que inlcuye
elementos_incluye_rtve_page = {
    "incluye_logo_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/img",
    "incluye_subtitulo_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/p[1]",
    "incluye_promo_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/p[2]",
    "incluye_precio_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/div",
    "incluye_btn_prueba_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/button",
    "incluye_terminos_rtve": "xpath://*[@id='app']/div[1]/div/div[1]/p[3]",
    "incluye_img1": "xpath://*[@id='app']/div[1]/div/div[2]/div[1]/div/img",
    "incluye_img2": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[1]/img",
    "incluye_img3": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[2]/img",
    "incluye_img4": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[1]/div[3]/img",
    "incluye_img5": "xpath://*[@id='app']/div[1]/div/div[2]/div[2]/div[2]/div/img",
}