elementos_home_page= {
    "home_ticker": "xpath=//section[@class='Headband fixed visible']//h2[1]",
    "home_ticker_close": "xpath=//img[@alt='close_icon']",
    "home_logo_cv": "xpath=//img[@alt='Clarovideo Logo']",
    "home_input_buscador": "xpath=//input[@placeholder='Buscar']",
    "home_lupa": "xpath=//i[@name='search']",
    "home_avatar": "xpath=//a[@class='dropdown-toggle dropdownUser menu_user custom-menu-user-style hidden-xs']//img[@class='menu_user--img']",
    "home_nodo_inicio": "xpath=//div[contains(text(),'Inicio')]",
    "home_nodo_catalogo": "xpath=//div[contains(text(),'Catálogo')]",
    "home_nodo_generos": "xpath=//div[contains(text(),'Géneros')]",
    "home_nodo_compra": "xpath=//div[contains(text(),'Compra y Renta')]",
    "home_nodo_canales": "xpath=//div[contains(text(),'Canales')]",
    "home_nodo_kids": "xpath=//img[@alt='Kids']",
    "home_nodo_miscontenidos": "xpath=//div[contains(text(),'Mis Contenidos')]",
}