textos_home_page = {
        "home_ticker": "Bienvenido a Claro video. Da clic aquí para conocer más planes y acceder a canales Premium.",
        "home_ticker_close": "",
        "home_logocv": "",
        "home_input_buscador": "",
        "home_lupa": "",
        "home_avatar": "",
        "home_nodo_inicio": "Inicio",
        "home_nodo_catalogo": "Catálogo",
        "home_nodo_generos": "Géneros",
        "home_nodo_compra": "Compra y Renta",
        "home_nodo_canales": "Canales",
        "home_nodo_kids": "",
        "home_nodo_miscontenidos": "Mis Contenidos",
        "home_nodo_musica": "",
        "home_superdestacados": "",
        "home_scroll_left_super": "",
        "home_scroll_right_super": "",
        "home_recomienda": "Claro video te recomienda",
        "home_carrusel_recomienda": "",
        "home_scroll_left_recomienda": "",
        "home_scroll_right_recomienda": "",
        "home_paramount": "Paramount+ incluido en Claro video",
        "home_carrusel_paramount": "",
        "home_scroll_left_paramount": "",
        "home_scroll_right_paramount": "",
        "home_terror": "Terror en tu pantalla",
        "home_carrusel_terror": "",
        "home_scroll_left_terror": "",
        "home_scroll_rigth_terror": "",
        "home_coleccion": "Colección Claro video",
        "home_carrrusel_coleccion": "VER AHORA",
        "home_scroll_left_coleccion": "",
        "home_scroll_rigth_coleccion": "",
        "home_familia": "Diversión en Familia",
        "home_carrusel_familia": "",
        "home_scroll_left_familia": "",
        "home_scroll_rigth_familia": "",
        "home_compra": "Top de Compra y Renta",
        "home_carrusel_compra": "",
        "home_scroll_left_compra": "",
        "home_scroll_rigth_compra": "",
        "home_maraton": "Maratón de Series",
        "home_carrusel_maraton": "",
        "home_scroll_left_maraton": "",
        "home_scroll_rigth_maraton": "",
        "home_nuevoen": "Lo Nuevo en Claro video",
        "home_carrusel_nuevoen": "",
        "home_scroll_left_nuevoen": "",
        "home_scroll_rigth_nuevoen": "",
        "home_parati": "Para ti",
        "home_carrusel_parati": "",
        "home_scroll_left_parati": "",
        "home_scroll_rigth_parati": "",
        "home_lomasvisto": "Lo más visto",
        "home_carrusel_lomasvisto": "",
        "home_scroll_left_lomasvisto": "",
        "home_scroll_rigth_lomasvisto": "",
        "home_series": "Las mejores series",
        "home_carrusel_series": "",
        "home_scroll_left_series": "",
        "home_scroll_rigth_series": "",
        "home_peliculas": "Las mejores películas",
        "home_carrusel_peliculas": "",
        "home_scroll_left_peliculas": "",
        "home_scroll_rigth_peliculas": "",
        "home_hbo": "HBO",
        "home_carrusel_hbo": "",
        "home_scroll_left_hbo": "",
        "home_scroll_rigth_hbo": "",
        "home_edye": "Edye",
        "home_carrusel_edye": "",
        "home_scroll_left_edye": "",
        "home_scroll_rigth_edye": "",
        "home_noggin": "Noggin",
        "home_carrusel_noggin": "",
        "home_scroll_left_noggin": "",
        "home_scroll_rigth_noggin": "",
        "home_atres": "ATRESplayer",
        "home_carrusel_atres": "",
        "home_scroll_left_atres": "",
        "home_scroll_rigth_atres": "",
        "home_picardia": "Picardía Nacional",
        "home_carrusel_picardia": "",
        "home_scroll_left_picardia": "",
        "home_scroll_rigth_picardia": "",
        "home_qello": "Qello Concerts",
        "home_carrusel_qello": "",
        "home_scroll_left_qello": "",
        "home_scroll_rigth_qello": "",
        "home_karaoke": "Stingray Karaoke",
        "home_carrusel_karaoke": "",
        "home_scroll_left_karaoke": "",
        "home_scroll_rigth_karaoke": "",
        "home_rtveplay": "rtveplay+",
        "home_carrusel_rtveplay": "",
        "home_scroll_left_rtveplay": "",
        "home_scroll_rigth_rtveplay": "",
        "home_starzplay": "Starzplay",
        "home_carrusel_starzplay": "",
        "home_scroll_left_starzplay": "",
        "home_scroll_rigth_starzplay": "",
        "home_accion": "Acción y Aventura",
        "home_carrusel_accion": "",
        "home_scroll_left_accion": "",
        "home_scroll_rigth_accion": "",
        "home_comedia": "Comedia",
        "home_carrusel_comedia": "",
        "home_scroll_left_comedia": "",
        "home_scroll_rigth_comedia": "",
        "home_suspenso": "Terror y Suspenso",
        "home_carrusel_suspenso": "",
        "home_scroll_left_suspenso": "",
        "home_scroll_rigth_suspenso": "",
        "home_cine": "Cine de Oro",
        "home_carrusel_cine": "",
        "home_scroll_left_cine": "",
        "home_scroll_rigth_cine": "",
        "home_ficcion": "Ciencia Ficción",
        "home_carrusel_ficcion": "",
        "home_scroll_left_ficcion": "",
        "home_scroll_rigth_ficcion": "",
        "home_drama": "Drama",
        "home_carrusel_drama": "",
        "home_scroll_left_drama": "",
        "home_scroll_rigth_drama": "",
        "home_romanticas": "Románticas",
        "home_carrusel_romanticas": "",
        "home_scroll_left_romanticas": "",
        "home_scroll_rigth_romanticas": "",
        "home_niños": "Niños",
        "home_carrusel_niños": "",
        "home_scroll_left_niños": "",
        "home_scroll_rigth_niños": "",
        "home_documentales": "Documentales",
        "home_carrusel_documentales": "",
        "home_scroll_left_documentales": "",
        "home_scroll_rigth_documentales": "",
        "home_latino": "Latinoamérica",
        "home_carrusel_latino": "",
        "home_scroll_left_latino": "",
        "home_scroll_rigth_latino": "",
        "home_anime": "Anime",
        "home_carrusel_anime": "",
        "home_scroll_left_anime": "",
        "home_scroll_rigth_anime": "",
        "home_infantil": "Series Infantiles",
        "home_carrusel_infantil": "",
        "home_scroll_left_infantil": "",
        "home_scroll_rigth_infantil": "",
        "home_seriesventa": "Series en Venta",
        "home_carrusel_seriesventa": "",
        "home_scroll_left_seriesventa": "",
        "home_scroll_rigth_seriesventa": "",
        "home_epoca": "Películas de Época",
        "home_carrusel_epoca": "",
        "home_scroll_left_epoca": "",
        "home_scroll_rigth_epoca": "",
        "home_musicales": "Musicales",
        "home_carrusel_musicales": "",
        "home_scroll_left_musicales": "",
        "home_scroll_rigth_musicales": "",
        "home_independiente": "Cine Independiente",
        "home_carrusel_independiente": "",
        "home_scroll_left_independiente": "",
        "home_scroll_rigth_independiente": "",
        "home_españolas": "Series Españolas",
        "home_carrusel_españolas": "",
        "home_scroll_left_españolas": "",
        "home_scroll_rigth_españolas": "",
        "home_musica": "Música y Conciertos",
        "home_carrusel_musica": "",
        "home_scroll_left_musica": "",
        "home_scroll_rigth_musica": "",
        #"home_footer": "",
        #"home_chat": "Chat Ayuda en Línea",
        #"home_tutoenvideo": "Tutoriales en video",
        #"home_tutoriales": "Tutoriales",
        #"home_preguntasfrecuentes": "Preguntas Frecuentes",
        #"home_requerimientos": "Requerimientos Mínimos",
        #"home_terminos": "Términos y Condiciones",
        #"home_politicas": "Políticas de Privacidad",
        #"home_promociones": "Términos de Promociones",
        #"home_licencia": "Licencia Usuario Final",
        #"home_logo_twitter": "",
        #"home_logo_fb": "",
        #"home_logo_google": "",
        #"home_logo_youtube": "",

}

textos_nodo_catalogo_page = {
    "catalogo_subnodo_paramount": "Paramount+",
    "catalogo_subnodo_peliculas": "Películas",
    "catalogo_subnodo_series": "Series",
    "catalogo_subnodo_musica": "Música",
    "catalogo_subnodo_deportes": "Deportes",
    "catalogo_subnodo_documentales": "Documentales",
    "catalogo_subnodo_latinoamericanas": "Latinoamérica",
    "catalogo_subnodo_karaoke": "Karaoke",
    "catalogo_carrsuel_destacados": "",
    "catalogo_recomienda": "Claro video te recomienda",
    "catalogo_carrsuel_recomienda": "",
    "catalogo_series": "Series de TV",
    "catalogo_carrsuel_series": "",
    "catalogo_accion": "Películas de Acción",
    "catalogo_carrusel_accion": "",
    "catalogo_comedia": "Películas de Comedia",
    "catalogo_carrusel_comedia": "",
    "catalogo_niños": "Niños",
    "catalogo_carrusel_niños": "",
    "catalogo_terror": "Películas de Terror",
    "catalogo_carrusel_terror": "",
    "catalogo_romanticas": "Películas Románticas",
    "catalogo_carrusel_romanticas": "",
    "catalogo_drama": "Películas de Drama",
    "catalogo_carrusel_drama": "",
    "catalogo_documentales": "Documentales",
    "catalogo_carrusel_documentales": "",
    "catalogo_conciertos": "Conciertos",
    "catalogo_carrusel_conciertos": "",
    "catalogo_lomasvisto": "Lo más visto",
    "catalogo_carrusel_lomasvisto": "",
}

textos_nodo_catalogo_paramount_page = {
    "catalogo_paramount_logo": "",
    "catalogo_paramount_bannerseries": "",
    "catalogo_paramount_bannerpaliculas": "",
    "catalogo_paramount_destacados": "",
    "catalogo_footer": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
    "catalogo_paramount_originales": "Paramount + Originales y Exclusivos",
    "catalogo_paramount_carrusel_originales": "",
    "catalogo_paramount_peliculas": "Películas",
    "catalogo_paramount_carrusel_peliculas": "",
    "catalogo_paramount_imperdibles": "Series Imperdibles",
    "catalogo_paramount_carrusel_imperdibles": "",
    "catalogo_paramount_inolvidables": "Series Inolvidables",
    "catalogo_paramount_carrusel_inolvidables": "",
    "catalogo_paramount_garantizadas": "Diversión Garantizada",
    "catalogo_paramount_carrusel_garantizadas": "",
    "catalogo_paramount_niños": "Para los más chiquitos",
    "catalogo_paramount_carrusel_niños": "",
    "catalogo_paramount_reality": "Reality Shows",
    "catalogo_paramount_carrusel_reality": "",
    "catalogo_paramount_comedia": "Series de Comedia",
    "catalogo_paramount_carrusel_comedia": "",
    "catalogo_paramount_lomasvisto": "Lo más visto",
    "catalogo_paramount_carrusel_lomasvisto": "",

}

textos_nodo_catalogo_peliculas_page = {
    "catalogo_peliculas_destacados": "",
    "catalogo_peliculas_terecomienda": "Claro video te recomienda",
    "catalogo_peliculas_carrusel_terecomienda": "",
    "catalogo_peliculas_mexicanas": "Mexicanas",
    "catalogo_perliculas__mexicanas": "",
    "catalogo_perliculas_accion": "Acción y Aventura",
    "catalogo_peliculas_carrusel_accion": "",
    "catalogo_peliculas_ficcion": "Ciencia Ficción y Fantasía",
    "catalogo_peliculas_carrusel_ficcion": "",
    "catalogo_peliculas_cine": "Cine de Oro",
    "catalogo_peliculas_carrusel_cine": "",
    "catalogo_peliculas_clasicas": "Clásicas",
    "catalogo_peliculas_carrusel_clasicas": "",
    "catalogo_peliculas_comedia": "Comedia",
    "catalogo_peliculas_carrusel_comedia": "",
    "catalogo_peliculas_deportes": "Deportes",
    "catalogo_peliculas_carrusel_deportes": "",
    "catalogo_peliculas_animados": "Dibujos Animados",
    "catalogo_peliculas_carrusel_animados": "",
    "catalogo_peliculas_drama": "Drama",
    "catalogo_peliculas_carrusel_drama": "",
    "catalogo_peliculas_familiares": "Familiares",
    "catalogo_peliculas_carrusel_familiares": "",
    "catalogo_peliculas_historicas": "Históricas",
    "catalogo_peliculas_carrusel_historicas": "",
    "catalogo_peliculas_infantiles": "Infantiles",
    "catalogo_peliculas_carrusel_infantiles": "",
    "catalogo_peliculas_internacional": "Internacional",
    "catalogo_peliculas_carrusel_internacional": "",
    "catalogo_peliculas_musicales": "Musicales",
    "catalogo_peliculas_carrusel_musicales": "",
    "catalogo_peliculas_epoca": "Películas de Época",
    "catalogo_peliculas_carrusel_epoca": "",
    "catalogo_peliculas_romanticas": "Románticas",
    "catalogo_peliculas_carrusel_romanticas": "",
    "catalogo_peliculas_suspenso": "Suspenso",
    "catalogo_pelicula_carrusel_suspensp": "",
    "catalogo_peliculas_terror": "Terror",
    "catalogo_peliculas_carrusel_terror": "",
    "catalogo_peliculas_lomasvisto": "Lo más visto",
    "catalogo_peliculas_carrusel_lomasvisto": "",

}

textos_nodo_catalogo_series_page = {
    "catalogo_series_destacados": "",
    "catalogo_series_recomienda": "Claro video te recomienda",
    "catalogo_series_carrusel_recomienda": "",
    "catalogo_series_maraton": "Maratón de Series",
    "catalogo_series_carrusel_maraton": "",
    "catalogo_series_soloencv": "Sólo en Claro video",
    "catalogo_series_carrusel_soloencv": "",
    "catalogo_series_mexicanas": "Mexicanas",
    "catalogo_series_carrusel_mexicanas": "",
    "catalogo_series_accion": "Acción y Aventura",
    "catalogo_series_carrusel_accion": "",
    "catalogo_series_anime": "Animé y Videojuegos",
    "catalogo_series_carrusel_anime": "",
    "catalogo_series_biograficas": "Biográficas",
    "catalogo_series_carrusel_biograficas": "",
    "catalogo_series_ficcion": "Ciencia Ficción",
    "catalogo_series_carrusel_ficcion": "",
    "catalogo_series_clasicas": "Clásicas",
    "catalogo_series_carrusel_clasicas": "",
    "catalogo_series_comicas": "Cómicas",
    "catalogo_series_carrusel_comicas": "",
    "catalogo_series_dramas": "Dramas",
    "catalogo_series_carrusel_dramas": "",
    "catalogo_series_españolas": "Españolas",
    "catalogo_series_carrusel_españolas": "",
    "catalogo_series_familiares": "Familiares",
    "catalogo_series_carrusel_familiares": "",
    "catalogo_series_historicas": "Históricas",
    "catalogo_series_carrusel_historicas": "",
    "catalogo_series_infantiles": "Infantiles",
    "catalogo_series_carrusel_infantiles": "",
    "catalogo_series_internacionesles": "Internacionales",
    "catalogo_series_carrusel_internacionales": "",
    "catalogo_series_latinoamericanas": "Latinoamericanas",
    "catalogo_series_carrusel_latinoamericanas": "",
    "catalogo_series_policiacas": "Policíacas",
    "catalogo_series_carrusel_policiacas": "",
    "catalogo_series_tv": "Programas de TV",
    "catalogo_series_carrusel_tv": "",
    "catalogo_series_documentales": "Series Documentales",
    "catalogo_series_carrusel_documentales": "",
    "catalogo_series_romanticas": "Románticas",
    "catalogo_series_carrusel_romanticas": "",
    "catalogo_series_suspenso": "Suspenso y Terror",
    "catalogo_series_carrusel_suspenso": "",
    "catalogo_series_lomasvisto": "Lo más visto",
    "catalogo_series_carrusel_lomasvisto": "VER AHORA",
}


textos_plan_selector_page = {
        "planselector_selecciona": "Selecciona un plan y comienza a disfrutar del mejor contenido",
        #"banner_claro_mensual": "",
        "logo_cv_claro_mensual": "",
        "precio_claro_mensual": "$115",
        "periodicidad_claro_mensual": "IVA incluido / mes",
        "promocion_claro_mensual": "30 días sin costo",
        "claro_mensual_btn_incluye?": "¿Qué incluye Claro video?",
        "claro_mensual_btn_suscribete": "SUSCRÍBETE MENSUAL",
        # "banner_claro_anual": "",
        "logo_cv_claro_anual": "",
        "precio_claro_anual": "$1149",
        "periodicidad_claro_anual": "IVA incluido / año",
        "promocion_claro_anual": "30 días sin costo",
        "claro_anual_btn_incluye?": "¿Qué incluye Claro video?",
        "claro_anual_btn_suscribete": "SUSCRÍBETE ANUAL",
        # "banner_fox": "",
        "logo_fox": "",
        "precio_fox": "$116",
        "periodicidad_fox": "IVA incluido / mes",
        "promocion_fox": "A partir del 4to. mes $162 / mes",
        "fox_btn_incluye?": "¿Qué incluye FOX SPORTS?",
        "fox_btn_suscribete": "CONTRATA FOX SPORTS",
        # "banner_noggin": "",
        "logo_noggin": "",
        "precio_noggin": "$49",
        "periodicidad_noggin": "IVA incluido / mes",
        "promocion_noggin": "Disfruta 7 días sin costo",
        "noggin_btn_incluye?": "¿Qué incluye Noggin?",
        "noggin_btn_suscribete": "CONTRATA NOGGIN",
        # "banner_edye": "",
        "logo_edye": "",
        "precio_edye": "$57",
        "periodicidad_edye": "IVA incluido / mes",
        "promocion_edye": "Disfruta 7 días de prueba para usuarios nuevos",
        "edye_btn_incluye?": "¿Qué incluye Edye?",
        "edye_btn_suscribete": "CONTRATA EDYE",
        # "banner_picardia": "",
        "logo_picardia": "",
        "precio_picardia": "$46",
        "periodicidad_picardia": "IVA incluido / mes",
        "promocion_picardia": "7 días sin costo",
        "picardia_btn_incluye?": "¿Qué incluye Picardía Nacional?",
        "picardia_btn_suscribete": "CONTRATA PICARDÍA",
        # "banner_karaoke": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_karaoke": "",
        "precio_karaoke": "$57",
        "periodicidad_karaoke": "IVA incluido / mes",
        "promocion_karaoke": "En Claro video",
        "karaoke_btn_incluye?": "¿Qué incluye Stingray Karaoke?",
        "karaoke_btn_suscribete": "CONTRATA STINGRAY KARAOKE",
        # "banner_qello": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_qello": "",
        "precio_qello": "$57",
        "periodicidad_qello": "IVA incluido / mes",
        "promocion_qello": "7 días sin costo",
        "qello_btn_incluye?": "¿Qué incluye Qello Concerts by Stingray?",
        "qello_btn_suscribete": "CONTRATA QELLO CONCERTS",
        # "banner_atres": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_atres": "",
        "precio_atres": "$57",
        "periodicidad_atres": "IVA incluido / mes",
        "promocion_atres": "7 días sin costo",
        "atres_btn_incluye?": "¿Qué incluye ATRESplayer?",
        "atres_btn_suscribete": "CONTRATA ATRESPLAYER",
        # "banner_hbo": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_hbo": "",
        "precio_hbo": "$149",
        "periodicidad_hbo": "IVA incluido / mes",
        "promocion_hbo": "Disfruta 7 días sin costo",
        "hbo_btn_incluye?": "¿Qué incluye HBO?",
        "hbo_btn_suscribete": "CONTRATA HBO",
        # "banner_indycar": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_indycar": "",
        "precio_indycar": "$490",
        "periodicidad_indycar": "IVA incluido / año",
        "promocion_indycar": "En Claro video",
        "indycar_btn_incluye?": "¿Qué incluye INDYCAR?",
        "indycar_btn_suscribete": "CONTRATA INDYCAR",
        # "banner_starzplay": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_starzplay": "",
        "precio_starzplay": "$89",
        "periodicidad_starzplay": "IVA Incluido / mes",
        "promocion_starzplay": "7 días sin costo",
        "starzplay_btn_incluye?": "¿Qué incluye Starzplay?",
        "starzplay_btn_suscribete": "CONTRATA STARZPLAY",
        # "banner_rtve": "//div[@style='background-image: url('https://clarovideocdn4.clarovideo.net/pregeneracion/cms/apa/uat_531eed34tvfy7b73a818a234/banner_cv_mensual.png?1618357147');')]",
        "logo_rtve": "",
        "precio_rtve": "$99",
        "periodicidad_rtve": "IVA Incluido / mes",
        "promocion_rtve": "Disfruta 7 días sin costo",
        "rtve_btn_incluye?": "¿Qué incluye RTVE play +?",
        "rtve_btn_suscribete": "CONTRATA RTVE PLAY +",
}

# Plan selector Claro video que incluye
textos_incluye_CV_page = {
    "incluye_logo_cv": "",
    "incluye_lasmejores": "Las mejores series y películas en tu suscripción y en todos tus dispositivos.",
    "incluye_logo_telmex": "",
    "incluye_verconcv_telemex": "Ver con Claro video",
    "incluye_logo_telcel": "",
    "inclute_verconcv_telcel": "Ver con Claro video",
    "incluye_promo_mensual": "30 días sin costo",
    "incluye_precio_mensual": "$115",
    "incluye_iva_mensual": "IVA incluido",
    "incluye_periodo_mensual": "/ mes",
    "incluye_btn_prueba_mensual": "PRUEBA 30 DÍAS SIN COSTO",
    "incluye_puedes_cancelar_mensual": "Puedes cancelar en cualquier momento",
    "incluye_promo_anual": "30 días sin costo",
    "incluye_precio_anual": "$1149",
    "incluye_iva_anual": "IVA incluido",
    "incluye_periodo_anual": "/ año",
    "incluye_btn_prueba_anual": "PRUEBA 30 DÍAS SIN COSTO",
    "incluye_puedes_cancelar_anual": "Puedes cancelar en cualquier momento",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector FOX que inlcuye
textos_incluye_fox_page = {
    "incluye_logo_fox": "",
    "incluye_subtitulo_fox": "FOX SPORTS con los mejores 3 canales deportivos en vivo y contenido deportivo bajo demanda.",
    "incluye_logo_telmex": "",
    "incluye_verfoxconcv_telmex": "Ver con FOX en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visitasitioweb_telcel": "Visita nuestro sitio web",
    "incluye_promo_fox": "A partir del 4to. mes $162 / mes",
    "incluye_precio_fox": "$116",
    "incluye_iva_fox": "IVA incluido",
    "incluye_periodo_fox": "/ mes",
    "incluye_btn_contrata_fox": "CONTRÁTALO AHORA",
    "incluye_puedes_cancelar_fox": "Puedes cancelar en cualquier momento. Vigencia de la promoción al 15 de Enero 2022",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector NOGGIN que inlcuye
textos_incluye_noggin_page = {
    "incluye_logo_noggin": "",
    "incluye_subtitulo_noggin": "El mejor contenido infantil para los más pequeños del hogar.",
    #"incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con Noggin en Claro video",
    #"incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_noggin": "Disfruta 7 días sin costo, después:",
    "incluye_precio_noggin": "$49",
    "incluye_iva_noggin": "IVA incluido",
    "incluye_periodo_noggin": "/ mes*",
    "incluye_btn_prueba_noggin": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_noggin": "*Este costo es adicional a tu suscripción de Claro video. Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector EDYE que inlcuye
textos_incluye_edye_page = {
    "incluye_logo_edye": "",
    "incluye_subtitulo_edye": "El primer servicio de contenido preescolar Premium para niños de 2 a 7 años.",
    "incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con Edye en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_edye": "Disfruta 7 días de prueba para usuarios nuevos, después:",
    "incluye_precio_edye": "$57",
    "incluye_iva_edye": "IVA incluido",
    "incluye_periodo_edye": "/ mes*",
    "incluye_btn_prueba_edye": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_edye": "*Este costo es adicional a tu suscripción de Claro video. Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector PICARDIA que inlcuye
textos_incluye_picardia_page = {
    "incluye_logo_picardia": "",
    "incluye_subtitulo_picardia": "Tenemos la mejor selección de cine mexicano y está bien picante.",
    "incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con Picardía Nacional en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_picardia": "7 días sin costo, después:",
    "incluye_precio_picardia": "$46",
    "incluye_iva_picardia": "IVA incluido",
    "incluye_periodo_picardia": "/ mes",
    "incluye_btn_prueba_picardia": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_picardia": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}

# Plan selector KARAOKE que inlcuye
textos_incluye_karaoke_page = {
    "incluye_logo_karaoke": "",
    "incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con Stingray Karaoke en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_karaoke": "En Claro video",
    "incluye_precio_karaoke": "$57",
    "incluye_iva_karaoke": "IVA incluido",
    "incluye_periodo_karaoke": "/ mes",
    "incluye_btn_prueba_karaoke": "CONTRATA STINGRAY KARAOKE",
    "incluye_terminos_karaoke": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector QELLO que inlcuye
textos_incluye_qello_page = {
    "incluye_logo_qello": "",
    "incluye_subtitulo_qello": "Los mejores conciertos con tus artistas, grupos y géneros favoritos.",
    "incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con Qello Concerts en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_qello": "7 días sin costo, después:",
    "incluye_precio_qello": "$57",
    "incluye_iva_qello": "IVA incluido",
    "incluye_periodo_qello": "/ mes",
    "incluye_btn_prueba_qello": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_qello": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector ATRES que inlcuye
textos_incluye_atres_page = {
    "incluye_logo_atres": "",
    "incluye_subtitulo_atres": "¡Contrata ATRESplayer! Podrás disfrutar de todos los programas de nuestra familia de canales (Antena 3 Internacional, Atreseries, ¡HOLA! TV y Atrescine) tanto en directo como Video Bajo Demanda sin publicidad. Incluye descarga de contenido para reproducir sin conexión a internet.",
    "incluye_promo_atres": "7 días sin costo, después:",
    "incluye_precio_atres": "$57",
    "incluye_iva_atres": "IVA incluido",
    "incluye_periodo_atres": "/ mes",
    "incluye_btn_prueba_atres": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_atres": "Puedes cancelar en cualquier momento",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector HBO que inlcuye
textos_incluye_hbo_page = {
    "incluye_logo_hbo": "",
    "incluye_subtitulo_hbo": "Las mejores series, estrenos y más.",
    "incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con HBO en Claro video",
    "incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_hbo": "Disfruta 7 días sin costo, después:",
    "incluye_precio_hbo": "$149",
    "incluye_iva_hbo": "IVA incluido",
    "incluye_periodo_hbo": "/ mes",
    "incluye_btn_prueba_hbo": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_hbo": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector INDYCAR que inlcuye
textos_incluye_indy_page = {
    "incluye_logo_indy": "",
    "incluye_subtitulo_indy": "Pisa el acelerador y prepárate para la temporada 2021 en vivo y en idioma original.",
    "incluye_promo_indy": "En Claro video",
    "incluye_precio_indy": "$490",
    "incluye_iva_indy": "IVA incluido",
    "incluye_periodo_indy": "/ año",
    "incluye_btn_prueba_indy": "SUSCRÍBETE AHORA",
    "incluye_terminos_indy": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector STARZPLAY que inlcuye
textos_incluye_starz_page = {
    "incluye_logo_starz": "",
    "incluye_subtitulo_starz": "Bienvenido a Starzplay. Aquí encontrarás todas la temporadas de nuestras series exclusivas, películas icónicas y muchos más contenidos alternativos, sin etiquetas e innovadores para maratonear. Todo esto con la posibilidad de descarga para verlo cuando y donde quieras.",
    "incluye_promo_starz": "Disfruta 7 días sin costo, después:",
    "incluye_precio_starz": "$89",
    "incluye_iva_starz": "IVA Incluido",
    "incluye_periodo_starz": "/ mes",
    "incluye_btn_prueba_starz": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_starz": "Puedes cancelar en cualquier momento.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}
# Plan selector RTVE que inlcuye
textos_incluye_rtve_page = {
    "incluye_logo_rtve": "",
    "incluye_subtitulo_rtve": "Bienvenido a RTVE play + en Claro video. La oferta premium donde encontrarás el mejor contenido de RTVE con temporadas completas de las series exitosas en España y en el mundo, películas para todos los gustos, programas especiales que marcaron época y muchos estrenos más. El hogar del entretenimiento en español está aquí.",
    #"incluye_logo_telmex": "",
    "incluye_ver_en_cv": "Ver con RTVE play + en Claro video",
    #"incluye_logo_telcel": "",
    "incluye_visita_sitio_web": "Visita nuestro sitio web",
    "incluye_promo_rtve": "Disfruta 7 días sin costo, después:",
    "incluye_precio_rtve": "$99",
    "incluye_iva_rtve": "IVA Incluido",
    "incluye_periodo_rtve": "/ mes",
    "incluye_btn_prueba_rtve": "PRUEBA 7 DÍAS SIN COSTO",
    "incluye_terminos_rtve": "Puedes cancelar en cualquier momento. No incluye la suscripción a Claro video, compra o renta de películas y series, ni algún otro servicio de suscripción.",
    "incluye_img1": "",
    "incluye_img2": "",
    "incluye_img3": "",
    "incluye_img4": "",
    "incluye_img5": "",
}